/*
 * generated by Xtext 2.23.0
 */
package de.itemis.tooling.xturtle.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import de.itemis.tooling.xturtle.XturtleRuntimeModule;
import de.itemis.tooling.xturtle.XturtleStandaloneSetup;
import org.eclipse.xtext.util.Modules2;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class XturtleIdeSetup extends XturtleStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new XturtleRuntimeModule(), new XturtleIdeModule()));
	}
	
}
