/*******************************************************************************
 * Copyright (c) 2013 AKSW Xturtle Project, itemis AG (http://www.itemis.eu).
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v10.html
 ******************************************************************************/
/*
* generated by Xtext
*/
package de.itemis.tooling.xturtle.ui.labeling;

import org.eclipse.xtext.resource.IEObjectDescription;
import org.eclipse.xtext.ui.label.DefaultDescriptionLabelProvider;

import de.itemis.tooling.xturtle.xturtle.XturtlePackage;

/**
 * Provides labels for a IEObjectDescriptions and IResourceDescriptions.
 * 
 * see http://www.eclipse.org/Xtext/documentation/latest/xtext.html#labelProvider
 */
public class XturtleDescriptionLabelProvider extends DefaultDescriptionLabelProvider {

/*
	//Labels and icons can be computed like this:
	
	String text(IEObjectDescription ele) {
	  return "my "+ele.getName();
	}
	 
    String image(IEObjectDescription ele) {
      return ele.getEClass().getName() + ".gif";
    }	 
*/
	public String text(IEObjectDescription ele) {
		StringBuilder b=new StringBuilder();
		b.append(ele.getQualifiedName().getLastSegment());
		if(ele.getEClass()!=XturtlePackage.Literals.TRIPLES){
			b.append(" (");
			b.append(ele.getQualifiedName().toString(""));
			b.append(")");
		}
		b.append(": ");
		b.append(ele.getEObjectURI().lastSegment());
		return b.toString();
		}
}
