/*
* generated by Xtext
*/
package de.itemis.tooling.xturtle.ui.outline;

import org.eclipse.xtext.ui.editor.outline.IOutlineNode;
import org.eclipse.xtext.ui.editor.outline.impl.DefaultOutlineTreeProvider;

import de.itemis.tooling.xturtle.xturtle.Triples;
import de.itemis.tooling.xturtle.xturtle.TurtleDoc;

/**
 * customization of the default outline structure
 * 
 */
public class XturtleOutlineTreeProvider extends DefaultOutlineTreeProvider {
	protected boolean _isLeaf(TurtleDoc doc) {
		return false;
	}

	protected boolean _isLeaf(org.eclipse.emf.ecore.EObject modelElement) {
		return true;
	}

	protected void _createNode(IOutlineNode parentNode, Triples modelElement) {
		createEObjectNode(parentNode, modelElement, labelProvider.getImage(modelElement.getSubject()), labelProvider.getText(modelElement.getSubject()), true);
	}

}
